on:
    push:
        branches:
            -   production
name: 🚀 Deploy Website to Production Server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Installing Node Modules Projects
      run:  npm ci
    
    - name: Building project
      run: npm run build --if-present
      env:
        CI: false
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.server}}
        username: ${{secrets.username}}
        password: ${{secrets.password }}
        server-dir: /httpdocs/
        # h